### ISSUE TITLE
Cant be installed

### ISSUE THREAD

**Issue by LeonBoettcher** [simonhuwiler/roccatvulcan#11]
I tried installing and using it but when i run `npm install` i get this error:

i have little experience on nodejs but it seems like it is trying to use python2

```
PS C:\Users\Leon\Downloads\roccatvulcan-master> npm install
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm ERR! code 1
npm ERR! path C:\Users\Leon\Downloads\roccatvulcan-master\node_modules\node-hid
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.14.2 | win32 | x64
npm ERR! gyp info find Python using Python version 3.11.3 found at "C:\Users\Leon\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:369:14)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:390:16
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:427:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19044
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\Leon\Downloads\roccatvulcan-master\node_modules\node-hid
npm ERR! gyp ERR! node -v v18.14.2
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok
```

**Comment by simonhuwiler** [comment]
Hi LeonMonkeygamer
Sorry for the delay. Were you able to get it running? I'll look at it in the coming days otherwise.

**Comment by LeonBoettcher** [comment]
I were able to get it run, but i dont rember now, what was wrong. Now it works fine, it works really well, thank you for creating it!

**Comment by simonhuwiler** [comment]
For your information: I published a new version. It should run now with most node versions (again).

**Comment by LeonBoettcher** [comment]
Would it be possible with your Libary to read out the current state of each button? I wanted to copy the Roccat the Roccat Swarm AIMO to my script, so that i can include effects without keep Roccat Swarm running

**Comment by simonhuwiler** [comment]
Hey @LeonMonkeygamer 
Yes, its possible to register a callback on key press event:

```javascript
keyboard = new RoccatVulcan({
  productId: 12440,
  layout: 'ch-de',
  onData: data => {
    console.log("Key", data.key);
    console.log("State", data.state);
  }
});
```

**Comment by LeonBoettcher** [comment]
Would it be possible to read the current colors of the keys send by roccat Swarm? I want to use the Roccat AImo to sync my other devices. Does you have an idea how to extend this lib?

**Comment by simonhuwiler** [comment]
Hmm, I'm not familiar with that. That would have to be reverse engineered. But also in Swarm I don't know of a function which excludes the color code. I guess this was not implemented by Roccat.

**Comment by LeonBoettcher** [comment]
Iam currently trying (or better, i was trying) to reverseeingeneir the Roccat Aimo color pattern. I really like it. But i cant use roccat swarm and your roccat repo at the same time, also i wanted to like make my background lightning (Adddresable LEDS Controlled with a ESP/arduino) to light in the same way, its not hard to programm the organic lightning from roccat, but i cant sync the keybourd and my lightning. There is no way to get the color of the LED Stripes synced with the keybourd. Either the timings are wrong or the keybourd is just lighting up diffrent. There are also no Informations, or people trying to use roccat aimo for other stuff. I Also tried to record my keyburd with a cam, extract the key colors and just use your lib to play this, turned out it looks really bad.
